### ISSUE TITLE
Some suggestions

### ISSUE THREAD

**Issue by FriendlyXuKun** [TheMagicFlute/TheMagicFlute.github.io#1]
In index.html:
In line 188:
'h3' -> 'h2'
because in  line 174 and line 154, 
these are all subheadings, and they both use tag h2.

**Comment by FriendlyXuKun** [comment]
In index.html:
In line 160, 164, 166, 168, 170:
In tag a, add 'target="_blank"'
because they aren't the parts of your page.

**Comment by TheMagicFlute** [comment]
ok, you can fork this repo and new a PR now.
